### ISSUE TITLE
Question about pose

### ISSUE THREAD

**Issue by xrenaa** [pmh47/textured-mesh-gen#2]
Hi, thanks for your work.

I find you use ground truth rotation during training, however, it seems that you did not mention this in the paper and supplement. Is is the case?

**Comment by pmh47** [comment]
This is discussed at the start of section 5 of the paper, noting that camera calibration in an object-centric frame subsumes the object pose (however it's not clear from fig. 2; I should adjust this). As you'll note from the code, the encoder model then predicts an adjustment to the approximate pose/calibration estimated from keypoints/vanishing points.
