### ISSUE TITLE
mesh_intersections Build CMake Error

### ISSUE THREAD

**Issue by yuta-tech** [pmh47/textured-mesh-gen#4]
I'm trying to build mesh_intersections.  
But when I execute cmake command with reference to README.md, an error occured.  

"cmake -DLIBIGL_WITH_CGAL=ON -DLIBIGL_WITH_CGAL=ON -DLIBIGL_WITH_OPENGL_GLFW=ON DCMAKE_BUILD_TYPE=Release -DGUROBI_ROOT=$GUROBI_ROOT -DMPFR_INCLUDE_DIR=$MPFR_INCLUDE_DIR -DMPFR_LIBRARIES=$MPFR_LIBRARIES .."  
(I added MPFR_INCLUDE_DIR and MPFR_LIBRARIES because another error occred )

The error is below  
  

CMake Error at CMakeLists.txt:26 (add_executable):
  Target "test_app" links to target "igl::opengl_glfw" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:25 (add_library):
  Target "push_ops" links to target "igl::opengl_glfw" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

What should I do?  
Thank you.

**Comment by pmh47** [comment]
`-DLIBIGL_WITH_OPENGL=ON` seems to be missing from your cmake command

**Comment by yuta-tech** [comment]
Thank you for replying.  
I didn't realize the mistake.  I was so careless. 
I made a mistake in the copy and paste.  
It's solved. I appreciate your help.
