### ISSUE TITLE
mesh_intersection make error

### ISSUE THREAD

**Issue by yuta-tech** [pmh47/textured-mesh-gen#5]
After successful cmake, I tried to make mesh_intersection.
But an error was happend.
The error is below,

**[ 82%] Linking CXX executable ../test_app
CMakeFiles/test_app.dir/mesh_intersections.cpp.o: In function `solve_for_offsets_gurobi(Eigen::Matrix<float, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1> const&, boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, boost::no_property, std::vector<IntersectionVertex, std::allocator<IntersectionVertex> >, boost::no_property, boost::listS> const&, Eigen::Array<float, -1, 1, 0, -1, 1> const&)':
mesh_intersections.cpp:(.text+0x4a19): undefined reference to `GRBModel::addVar(double, double, double, char, std::string)'
mesh_intersections.cpp:(.text+0x4b2c): undefined reference to `GRBModel::addConstr(GRBTempConstr const&, std::string)'
mesh_intersections.cpp:(.text+0x559c): undefined reference to `GRBModel::addConstr(GRBTempConstr const&, std::string)'
collect2: error: ld returned 1 exit status
CMakeFiles/test_app.dir/build.make:153: recipe for target '../test_app' failed
make[2]: *** [../test_app] Error 1
CMakeFiles/Makefile2:185: recipe for target 'CMakeFiles/test_app.dir/all' failed
make[1]: *** [CMakeFiles/test_app.dir/all] Error 2
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2**

My environment is
Ubuntu 16.04 LTS
gcc 7.1.0
cmake  3.17.1
Gurobi 8.1.1
tensorflow 2.2.0

**Comment by pmh47** [comment]
Probably gurobi is not found/loaded at run time. Ensure `LD_LIBRARY_PATH` includes the folder containing libgurobi81.so

**Comment by yuta-tech** [comment]
Thank you for replying.
I found libgurobi81.so in my LD_LIBRARY_PATH.

$ echo $LD_LIBRARY_PATH
/usr/local/cuda-10.1/lib64:/home/user1/gurobi811/linux64/lib

And also I tried to recompile libgurobi_c++.a with reference to https://support.gurobi.com/hc/en-us/articles/360039093112-C-compilation-on-Linux .
But I couldn't solve it. Is my gcc version not correct? Or any typo?
My gcc version is 7.1.0 because my gcc 5.4.0 give an error about "for (auto [])".
So I want to know about your gcc version.

**Comment by yuta-tech** [comment]
I soleved it by rewrite CMakeList.txt line 14.

`find_library(GUROBI_CXX_LIB "gurobi_g++5.2" HINTS "${GUROBI_ROOT}/lib")` to
`find_library(GUROBI_CXX_LIB "gurobi_g++7.1" HINTS "${GUROBI_ROOT}/lib")`

This gurobi_g++7.1 is recompiled(with -fPIC option) libgurobi_c++.a. And I renamed it corresponding my gcc version.

**Comment by yuta-tech** [comment]
rewriting "gurobi_g++4.2" is easier than recompile to solve. In my case gcc7.
